#ifndef MCPPROTOCOL_HANDSHAKE_CLIENT_BOUND_HPP
#define MCPPROTOCOL_HANDSHAKE_CLIENT_BOUND_HPP

namespace mcp {

}

#include "generated/login_client.inl"

#endif //MCPPROTOCOL_HANDSHAKE_CLIENT_BOUND_HPP
